### ISSUE TITLE
UnsatisfiedLinkError on Mac

### ISSUE THREAD

**Issue by jazamb** [kristian/system-hook#27]
I was trying to run my application (JAR file) with system hook 3.2 and I got an UnsatisfiedLinkError. I never got this error on my windows computer, but for some reason I get this error on my iMac.
~~~~
Exception in thread "main" java.lang.UnsatisfiedLinkError: lib: libsystemhook-darwin-x86_64.dylib not found in lib directory
	at lc.kra.system.LibraryLoader.loadLibrary(LibraryLoader.java:86)
	at lc.kra.system.keyboard.GlobalKeyboardHook.<init>(GlobalKeyboardHook.java:98)
	at lc.kra.system.keyboard.GlobalKeyboardHook.<init>(GlobalKeyboardHook.java:86)
	at noui.control.input.Keyboard<clinit>(Keyboard.java:53)
	at noui.control.MainController.register(MainController.java:74)
	at noui.Main.main(Main.java:115)
~~~~
Any help would be appreciated

**Comment by kristian** [comment]
Hello, see #20. Linux / Mac native support was actually never added to this library due to time constraints. Unfortunately I don‘t think I‘ll find the time anywhere soon. I will take this issue as a enhancement request for the Mac part, the same as #20 is for Linux. Please feel free to provide me with a pull request in case you‘d like to start with an implementation. Thanks!

**Comment by kristian** [comment]
Has been four years, to it is fair to say, if no one issues a PR, Linux & Mac OSX support likely will not be provided anytime soon. See #49. Closing as "wont-fix" for now. Sorry.
