### ISSUE TITLE
UnsatisfiedLinkError

### ISSUE THREAD

**Issue by johndev4** [kristian/system-hook#41]
Hi, I have an error:
Exception in thread “main” java.lang.UnsatisfiedLinkError: lib: systemhook-windows-amd64.dll not found in lib directory
at lc.kra.system.LibraryLoader.loadLibrary(LibraryLoader.java:86)
at lc.kra.system.keyboard.GlobalKeyboardHook.(GlobalKeyboardHook.java:113)
at lc.kra.system.keyboard.GlobalKeyboardHook.(GlobalKeyboardHook.java:101)

what should I do?

**Comment by kristian** [comment]
Hello @johndev4, are you using the library as an dependency, or did you just copy the source files to your project. If you have done the second, you will have to provide the library .dll files alongside your project. These are included in the release JAR provided in the releases section or on Appveyor. Hope this helps.

**Comment by johndev4** [comment]
Hi @kristian, I just copy the source files to my project. Where can I get the library .dll files?

**Comment by kristian** [comment]
You may download them from AppVeyor, see:

For x86: https://ci.appveyor.com/project/kristian/system-hook/build/job/nb4na3f3xj4oghk7/artifacts
For x64: https://ci.appveyor.com/project/kristian/system-hook/build/job/o4ulb68o1nvv70ll/artifacts

Hope this helps. Regards,
Kristian
