### ISSUE TITLE
NoClassDefFoundError with GlobalKeyListener

### ISSUE THREAD

**Issue by Hayato175** [kristian/system-hook#47]
Hello,

I try to use your library in my project.
When I launch my project on Intellij, the program works well but when I export my project as JAR, the following exception appears :
`Exception in thread "main" java.lang.NoClassDefFoundError: lc/kra/system/keyboard/event/GlobalKeyListener
	at fr.author.simpleKeyLogger.modele.Main.Main.main(Main.java:31)
Caused by: java.lang.ClassNotFoundException: lc.kra.system.keyboard.event.GlobalKeyListener
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 1 more`
My OS is Windows 10 and the version of my Java Compiler is 8. I use "system-hook-3.6.jar" (Notice that GlobalKeyboardHook doesn't create Exception).

Could you tell me if you know how to fix it please ?

**Comment by kristian** [comment]
Hello @Hayato175, the library is now available on Maven Central, other than on GitHub, can you please try to consuming it from there?

If you build your JAR, you'll have to also include all other JAR dependencies into the JAR you export as a so called "uber-jar" or "fat-jar". Otherwise the library will not find the class files required to launch. Hope this helps.
