### ISSUE TITLE
ibsystemhook-linux-amd64.so not found (Maven Ubuntu)

### ISSUE THREAD

**Issue by sl5net** [kristian/system-hook#49]
i got error if i try run it out of IDE (jetbrains IDE):

```
~/.jdks/openjdk-15.0.2/bin/java -javaagent:~/ideaPro/idea-IU-203.7148.57/lib/idea_rt.jar=44441:~/ideaPro/idea-IU-203.7148.57/bin -Dfile.encoding=UTF-8 -classpath ~/IdeaProjects/system-hook/target/classes lc.kra.system.keyboard.example.GlobalKeyboardExample
Exception in thread "main" java.lang.UnsatisfiedLinkError: lib: libsystemhook-linux-amd64.so not found in lib directory
	at lc.kra.system.LibraryLoader.loadLibrary(LibraryLoader.java:85)
	at lc.kra.system.keyboard.GlobalKeyboardHook.<init>(GlobalKeyboardHook.java:118)
	at lc.kra.system.keyboard.GlobalKeyboardHook.<init>(GlobalKeyboardHook.java:106)
	at lc.kra.system.keyboard.example.GlobalKeyboardExample.main(GlobalKeyboardExample.java:34)

```

**Comment by Hellosager** [comment]
There is currently no support for other OS besides Windows.

Refer to:
https://github.com/kristian/system-hook/issues/33#issuecomment-508064153

**Comment by kristian** [comment]
Thanks @Hellosager. Linux / Mac OSX support has been in the pipeline for so long, that it is fair to say, it might never come for this library. PRs are highly welcome, for now this issue is closed and "wont-fix". Sorry.
